# -*- coding: utf-8 -*-
"""
/***************************************************************************.

 StressorReceptorCalc
                                 A QGIS plugin
 This calculates a response layer from stressor and receptor layers
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-04-19
        copyright            : (C) 2021 by Integral Consultsing
        email                : cgrant@integral-corp.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load StressorReceptorCalc class from file StressorReceptorCalc.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .stressor_receptor_calc import StressorReceptorCalc

    return StressorReceptorCalc(iface)
